name: 'build kernel'
on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs.branch }}

      - name: build_step
        run: |
          echo "build"
          build_dir=$( pwd )
          pushd ../
          wget 'https://mirrors.edge.kernel.org/pub/tools/crosstool/files/bin/x86_64/13.2.0/x86_64-gcc-13.2.0-nolibc-ia64-linux.tar.xz' -O ./tarball.tar.xz
          wget 'https://raw.githubusercontent.com/johnny-mnemonic/linux-stable-rc/__mirror/make-kernel.bash' && chmod +x make-kernel.bash
          wget 'https://raw.githubusercontent.com/johnny-mnemonic/linux-stable-rc/__mirror/rx2620-rx2660-rx2800-i2-combined-localmodconfig'
          wget 'https://raw.githubusercontent.com/johnny-mnemonic/linux-stable-rc/__mirror/ia64-linux-workaround-ice-with-gcc-13.patch'
          tar -xf tarball.tar.xz
          ls -l
          PATH=$PATH:$PWD/gcc-13.2.0-nolibc/ia64-linux/bin
          popd
          patch -p1 < ../ia64-linux-workaround-ice-with-gcc-13.patch || true
          BRANCH="${{ inputs.branch }}"
          KERNEL_VERSION=$( git log --oneline | head -n1 | grep -o "Linux\ .*\-rc.*" )
          pushd ../
          echo "| STATUS | BRANCH | VERSION |" >> $GITHUB_STEP_SUMMARY
          echo "| ------ | ------ | ------- |" >> $GITHUB_STEP_SUMMARY
          if time ./make-kernel.bash ./rx2620-rx2660-rx2800-i2-combined-localmodconfig ia64 ${build_dir}; then
            echo "| :white_check_mark: | $BRANCH | $KERNEL_VERSION" | >> $GITHUB_STEP_SUMMARY
          else
            echo "| :x: | $BRANCH | $KERNEL_VERSION | >> $GITHUB_STEP_SUMMARY
          fi
