name: 'build_ski'
on:
  workflow_dispatch:

jobs:
  build_ski:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          repository: johnny-mnemonic/ski
          ref: master
          path: ski

      - name: install_prereqs
        run: |
          sudo apt update
          # basic build depends:
          sudo apt install binutils-dev libelf-dev libiberty-dev libncurses-dev
          # dev-only depends:
          sudo apt install autoconf autoconf-archive automake flex bison gperf pkg-config

      - name: Generate ./configure
        run: |
          cd ski
          ./autogen.sh

      - name: Configure
        run: |
          cd ski
          ./configure --prefix=$PWD/install

      - name: Build
        run: |
          cd ski
          make -j$(nproc)

      - name: Install
        run: |
          cd ski
          make -j$(nproc) install
