name: 'signal_build_linux_4_19_y'
on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: echo
        run: |
          echo "build linux-4.19.y"
