name: 'linux-6.1.y'
on:
  workflow_run:
    workflows: [linux_6_1_y_rc_ready]
    types: [completed]
  workflow_dispatch:

jobs:
  build:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses:  ./.github/workflows/build-kernel.yml
    with:
      branch: 'linux-6.1.y'
