name: 'linux-5.4.y'
on:
  workflow_run:
    workflows: [signal_build_linux_5_4_y]
    types: [completed]
  workflow_dispatch:

jobs:
  build:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses:  ./.github/workflows/build-kernel.yml
    with:
      branch: 'linux-5.4.y'
